service: path-2-mastery-api

plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-2

#  stage: dev

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  include:
    - lessons.json
#    - include-me.js
#    - include-me-dir/**
  exclude:
    - lessons.json
#    - exclude-me-dir/**

functions:
  read_lessons:
    handler: lessons_handler.all_lessons
    events:
      - http:
          path: lessons
          method: get
          cors: true


custom:
  customDomain:
    domainName: api.faros.io
    certificateName: faros.io
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
